task:
  task_name: tidyup
  display_name: Tidyup
  description: Copied Preset From HSR_GUI
  author: erasers

programs:
  navigation:
    display_name: Navigation
    description: ""
    command:
      template: roslaunch navigation_start navigation.launch
      kill: ""
      variables: ""

  vision:
    display_name: Vision
    description: ""
    command:
      template: roslaunch erasers_vision erasersvision.launch
      kill: ""
      variables: {}

  yolo:
    display_name: Yolo
    description: Object detection and recognition for tidypu
    command:
      template: 'docker compose -f /home/roboworks/erasers_ws/src/hsr/yolo-ros-docker/docker-compose.yml up'
      kill: "docker compose -f /home/roboworks/erasers_ws/src/hsr/yolo-ros-docker/docker-compose.yml down"
      variables:
        home:
          type: env
          key: HOME

  tidyup:
    display_name: Tidyup
    description: ""
    command:
      template: 'roslaunch robot_tasks tidyup.launch start_time:=${start_time} task1_time:=${task1_time} start_state:=${start_state} search_location:=${search_location}'
      kill: ""
      variables:
        start_time:
          type: unixtime
          default: -1
        task1_time:
          type: duration
          default: 900
        start_state:
          type: array
          options: ["FULLTEST", "TASK1", "TASK2A", "TASK2B", "TASKBOSS"]
          default: "FULLTEST"
        search_location:
          type: array
          options: ["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","90","91"]
          default: "0"
